### ISSUE TITLE
Definition for CBID

### ISSUE THREAD

**Issue by ekr** [SWAN-community/swan#2]
https://github.com/SWAN-community/swan/blob/main/data-flows.md talks about the CBID but this doesn't seem to be defined anywhere.

**Comment by jwrosewell** [comment]
Common Browser ID (CBID) was the name used for the SWID during initial development. It was changed to SWID to avoid any confusion with any other sources of common browser identifiers in the future. This document was missed in the update. It's now been changed. Thanks for raising.
